server {
    listen 80;
    server_name localhost;

    # Aponta para a pasta ANTES do /edi
    root /usr/share/nginx/html;
    
    # Inclui os tipos de ficheiro corretos (crucial para JS/CSS)
    include /etc/nginx/mime.types;

    location /edi/ {
        # Garante que procura dentro de /usr/share/nginx/html/edi/
        index index.html;
        # Se não achar o ficheiro, tenta o index.html da pasta edi
        try_files $uri $uri/ /edi/index.html;
    }

    # Bloco específico para Assets para evitar que retornem o index.html em caso de erro
    location /edi/assets/ {
        root /usr/share/nginx/html;
        try_files $uri =404; # Se não existir o .js, dá 404 em vez de quebrar com E.map
        access_log off;
        expires 1y;
    }
}